blank_issues_enabled: false
contact_links:
  - name: Discord Chat
    url: https://discord.gg/jUKyRxyedx
    about: Ask questions and discuss with other Vite users in real time.
  - name: Questions & Discussions
    url: https://github.com/bn-kvh/kvh/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
